C====================================================================
C sample_talk.cin
C====================================================================
C
C TALK TO DECLARATIONS FOR FLAGS
C
        logical*1 TRIGFLAG, TELEFLAG, C2TRGFLAG
	logical*1 TELLINAFLAG, PIZZAFLAG !This are only prod2root
	logical*1 ECLSFLAG
	logical BPOSFLAG
C
	common /sammenu/ TRIGFLAG, TELEFLAG, C2TRGFLAG,
     &	 TELLINAFLAG, PIZZAFLAG, ECLSFLAG, BPOSFLAG
